- name: Configure Flatpak
  become: true
  ansible.builtin.import_playbook: flatpak/configure.yml

- name: Install wanted flatpaks
  become: true
  ansible.builtin.import_playbook: flatpak/install.yml

- name: Configure openSUSE repos
  become: true
  ansible.builtin.import_playbook: opensuse/configure.yml

- name: Install wanted packages
  become: true
  ansible.builtin.import_playbook: opensuse/install.yml